spring.application.name=DevProject
server.port=8081

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
#spring.main.web-application-type=none
# ===============================
# DataSource (Gabia MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://my8003.gabiadb.com:3306/bootcamp?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=bootcamp
spring.datasource.password=bassul78354
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.web.error.include-message=always
spring.web.error.include-binding-errors=always


mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.hdcd.board
mybatis.configuration.map-underscore-to-camel-case=true